version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/myapp
    container_name: app-container-test
    restart: unless-stopped
    volumes:
      - ./:/usr/src/myapp
    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-container-test
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    external:
      name: external-example